name: AutoBuild

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout for CI 🛎️"
        uses: actions/checkout@v4

      - name: "Set up JDK 21 📦"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Build with Gradle 🏗️"
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          name: Release ${{ github.run_id }}
          body: |
            ## HuskTown - Build ${{ github.run_id }}

            **Build Date:** ${{ github.event.head_commit.timestamp }}
          append_body: false
          files: target/**/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
